name: Integration tests
"on":
  push: null
  schedule:
    - cron: 0 */24 * * *
  workflow_dispatch:
  watch:
    types:
      - started
env:
  config: Release
jobs:
  integration-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Build using .NET Core
        run: dotnet build Octokit.GraphQL.sln -c ${{ env.config }}
      - name: Run integration tests
        run: >-
          dotnet test -c ${{ env.config }} --no-build /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover
          /p:Exclude="[Octokit.GraphQL]Octokit.GraphQL.*"
          .\Octokit.GraphQL.IntegrationTests\Octokit.GraphQL.IntegrationTests.csproj
        env:
          OCTOKIT_GQL_OAUTHTOKEN: ${{ secrets.OCTOKIT_GQL_OAUTHTOKEN }}
          OCTOKIT_GQL_GITHUBUSERNAME: ${{ secrets.OCTOKIT_GQL_GITHUBUSERNAME }}
